# Generated by Django 2.1.15 on 2022-08-23 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='CDMX', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Up to 10 digits allowed.', regex='^\\?1?\\d{10,10}$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('TACOS', 'TACOS'), ('Italian', 'Italian'), ('Fast food', 'Fast food')], default='Pizza', max_length=50),
        ),
    ]
