# Generated by Django 2.1.15 on 2022-08-23 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20220822_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Up to 10 digits allowed.', regex='^[0-9]*$')]),
        ),
    ]
