# Generated by Django 2.1.15 on 2022-08-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20220822_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Tacos', 'Tacos'), ('Italian', 'Italian'), ('Fast food', 'Fast food')], default='Pizza', max_length=50),
        ),
    ]
